### ISSUE TITLE
How do I fix color and resolution issues

### ISSUE THREAD

**Issue by fangdichan** [dahliaOS/fimage#1]
I ran the fimage using./fimage-gui 4096 in vm (ubuntu20.04). The color was not correct and the resolution was not correct:
![image](https://user-images.githubusercontent.com/43296986/120292131-9c013400-c2f6-11eb-9c66-363b8e79b995.png)
![image](https://user-images.githubusercontent.com/43296986/120292753-25b10180-c2f7-11eb-950b-d0007381b2ee.png)

but using the screenshort tool, I did get the right image
![image](https://user-images.githubusercontent.com/43296986/120293057-7b85a980-c2f7-11eb-9070-3cfd20840305.png)

./ffx-linux-x64 platform preflight
Running pre-flight checks...

  [✓] Found all needed build dependencies: curl, git, unzip

  [!] Did not find tested and supported graphics acceleration hardware. Usage of the
      graphical Fuchsia emulator (`fx vdl start`) may fall back to a slow software
      renderer. The terminal emulator (`fx qemu`) is unaffected.
      Found the following chipsets: Cirrus Logic GD 5446
      Only a small set of chipsets are officially supported:
      https://fuchsia.dev/fuchsia-src/get-started/set_up_femu#supported-hardware

  [✓] Found tuntap device named 'qemu' for current user

There were some warnings, but you can still carry on. Continue at https://fuchsia.dev/fuchsia-src/get-started

**Comment by nmcain** [comment]
I see a "Cirrus Logic GD 5446" as your GPU, are you virtualizing Ubuntu?

**Comment by fangdichan** [comment]
> I see a "Cirrus Logic GD 5446" as your GPU, are you virtualizing Ubuntu?

Yes, I only have this normal graphics card, my physical machine running CentOS, the CPU is Intel(R) Xeon(R) GOLD 6130, therefore is Ubuntu 20.04 running in VM, and nested is enabled, enabling me to run VM in VM

**Comment by nmcain** [comment]
I see. FImage relies on physical hardware for rendering, I'm surprised that you were even able to display things on the screen.

**Comment by fangdichan** [comment]
> I see. FImage relies on physical hardware for rendering, I'm surprised that you were even able to display things on the screen.

Do you mean to show that this effect has been achieved by miracle?
If so, I will not pay attention to the color problem. Is there any way to adjust the resolution? When I change the -window-size parameter, it does not change the resolution of Fuchsia, only the size of the terminal window changed.

**Comment by nmcain** [comment]
I don't think the resolution of Fuchsia itself can be changed, you can attempt to mess with [this kernel parameter](https://fuchsia.dev/fuchsia-src/reference/kernel/kernel_cmdline?hl=en#bootloaderfbreswxh), it might be helpful

**Comment by fangdichan** [comment]
> I don't think the resolution of Fuchsia itself can be changed, you can attempt to mess with [this kernel parameter](https://fuchsia.dev/fuchsia-src/reference/kernel/kernel_cmdline?hl=en#bootloaderfbreswxh), it might be helpful

I have tried this and it still doesn't work, I have also tested the FEMU on my machine and had the same problem, so I suspect there may be something wrong with my graphics card, I will try again later when I have a better machine. Thank you
