### ISSUE TITLE
How to cleanly shut down the VM, for restart?

### ISSUE THREAD

**Issue by nealmcb** [dahliaOS/fimage#3]
I haven't figured out how to exit the VM.  When I use Ctrl-Z to suspend it and then kill it, the network ends up busy,

```
qemu-system-x86_64-headless: could not configure /dev/net/tun (qemu): Device or resource busy
```

and I resort to:

```
sudo ip link delete qemu
sudo ip link delete brqemu
./network-config
```

How can we bring it down cleanly?  Perhaps we can modify the `network-config` script to clean up also?

**Comment by nmcain** [comment]
Would you mind making a PR with that modification to the readme? Otherwise I can just drop that text into it over here.

**Comment by nealmcb** [comment]
Oops - I thought I already opened a PR for my commit. Done now.
